org: akluu
app: auto-number-sign-up
service: auto-number-sign-up
frameworkVersion: '3'

plugins:
   - serverless-python-requirements

custom:
  pythonRequirements:
     dockerizePip: non-linux

package:
  patterns:
    - '!node_modules/**'
    - '!venv/**'

provider:
  name: aws
  region: us-west-1
  runtime: python3.8
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - 'dynamodb:*'
          Resource: "*"
        - Effect: Allow
          Action:
            - 'SNS:*'
          Resource: '*'


functions:
  addUser:
    handler: handler.handler
    events:
      - http:
          path: /user
          method: post
          cors: true

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: userId
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: phoneNumber
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
            Projection:
              ProjectionType: 'ALL'
          - IndexName: subscriptionARN
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
            Projection:
              ProjectionType: 'ALL'
        BillingMode: "PAY_PER_REQUEST"


        