org: akluu
app: auto-number-sign-up
service: auto-number-sign-up
frameworkVersion: '3'

provider:
  name: aws
  region: us-west-1
  runtime: python3.8
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - 'dynamodb:PutItem'
            - 'dynamodb:Get*'
            - 'dynamodb:Scan*'
            - 'dynamodb:UpdateItem'
            - 'dynamodb:DeleteItem'
          Resource: "arn:aws:dynamodb:us-west-1:*:table/users"


functions:
  addUser:
    handler: handler.handler
    events:
      - http:
          path: /user
          method: post
          cors: true

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: userId
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: phoneNumber
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
            Projection:
              ProjectionType: 'ALL'
          - IndexName: subscriptionARN
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
            Projection:
              ProjectionType: 'ALL'
        BillingMode: "PAY_PER_REQUEST"
        